# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_HelloWorldWrapper')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_HelloWorldWrapper')
    _HelloWorldWrapper = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_HelloWorldWrapper', [dirname(__file__)])
        except ImportError:
            import _HelloWorldWrapper
            return _HelloWorldWrapper
        try:
            _mod = imp.load_module('_HelloWorldWrapper', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _HelloWorldWrapper = swig_import_helper()
    del swig_import_helper
else:
    import _HelloWorldWrapper
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _HelloWorldWrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _HelloWorldWrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _HelloWorldWrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _HelloWorldWrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _HelloWorldWrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _HelloWorldWrapper.SwigPyIterator_copy(self)

    def next(self):
        return _HelloWorldWrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _HelloWorldWrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _HelloWorldWrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _HelloWorldWrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _HelloWorldWrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _HelloWorldWrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _HelloWorldWrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _HelloWorldWrapper.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class HelloWorld(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HelloWorld, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HelloWorld, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _HelloWorldWrapper.delete_HelloWorld
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _HelloWorldWrapper.new_HelloWorld(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __eq__(self, x):
        return _HelloWorldWrapper.HelloWorld___eq__(self, x)

    def __ne__(self, x):
        return _HelloWorldWrapper.HelloWorld___ne__(self, x)

    def index(self, *args):
        return _HelloWorldWrapper.HelloWorld_index(self, *args)

    def message(self, *args):
        return _HelloWorldWrapper.HelloWorld_message(self, *args)
    if _newclass:
        getMaxCdrSerializedSize = staticmethod(_HelloWorldWrapper.HelloWorld_getMaxCdrSerializedSize)
    else:
        getMaxCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getMaxCdrSerializedSize
    if _newclass:
        getCdrSerializedSize = staticmethod(_HelloWorldWrapper.HelloWorld_getCdrSerializedSize)
    else:
        getCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getCdrSerializedSize

    def serialize(self, cdr):
        return _HelloWorldWrapper.HelloWorld_serialize(self, cdr)

    def deserialize(self, cdr):
        return _HelloWorldWrapper.HelloWorld_deserialize(self, cdr)
    if _newclass:
        getKeyMaxCdrSerializedSize = staticmethod(_HelloWorldWrapper.HelloWorld_getKeyMaxCdrSerializedSize)
    else:
        getKeyMaxCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getKeyMaxCdrSerializedSize
    if _newclass:
        isKeyDefined = staticmethod(_HelloWorldWrapper.HelloWorld_isKeyDefined)
    else:
        isKeyDefined = _HelloWorldWrapper.HelloWorld_isKeyDefined

    def serializeKey(self, cdr):
        return _HelloWorldWrapper.HelloWorld_serializeKey(self, cdr)
HelloWorld_swigregister = _HelloWorldWrapper.HelloWorld_swigregister
HelloWorld_swigregister(HelloWorld)

def HelloWorld_getMaxCdrSerializedSize(current_alignment=0):
    return _HelloWorldWrapper.HelloWorld_getMaxCdrSerializedSize(current_alignment)
HelloWorld_getMaxCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getMaxCdrSerializedSize

def HelloWorld_getCdrSerializedSize(data, current_alignment=0):
    return _HelloWorldWrapper.HelloWorld_getCdrSerializedSize(data, current_alignment)
HelloWorld_getCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getCdrSerializedSize

def HelloWorld_getKeyMaxCdrSerializedSize(current_alignment=0):
    return _HelloWorldWrapper.HelloWorld_getKeyMaxCdrSerializedSize(current_alignment)
HelloWorld_getKeyMaxCdrSerializedSize = _HelloWorldWrapper.HelloWorld_getKeyMaxCdrSerializedSize

def HelloWorld_isKeyDefined():
    return _HelloWorldWrapper.HelloWorld_isKeyDefined()
HelloWorld_isKeyDefined = _HelloWorldWrapper.HelloWorld_isKeyDefined

import fastdds
GEN_API_VER = _HelloWorldWrapper.GEN_API_VER
class HelloWorldPubSubType(fastdds.TopicDataType):
    __swig_setmethods__ = {}
    for _s in [fastdds.TopicDataType]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HelloWorldPubSubType, name, value)
    __swig_getmethods__ = {}
    for _s in [fastdds.TopicDataType]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, HelloWorldPubSubType, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _HelloWorldWrapper.new_HelloWorldPubSubType()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _HelloWorldWrapper.delete_HelloWorldPubSubType
    __del__ = lambda self: None

    def serialize(self, data, payload):
        return _HelloWorldWrapper.HelloWorldPubSubType_serialize(self, data, payload)

    def deserialize(self, payload, data):
        return _HelloWorldWrapper.HelloWorldPubSubType_deserialize(self, payload, data)

    def getSerializedSizeProvider(self, data):
        return _HelloWorldWrapper.HelloWorldPubSubType_getSerializedSizeProvider(self, data)

    def getKey(self, data, ihandle, force_md5=False):
        return _HelloWorldWrapper.HelloWorldPubSubType_getKey(self, data, ihandle, force_md5)

    def createData(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_createData(self)

    def deleteData(self, data):
        return _HelloWorldWrapper.HelloWorldPubSubType_deleteData(self, data)

    def is_bounded(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_is_bounded(self)

    def is_plain(self):
        return _HelloWorldWrapper.HelloWorldPubSubType_is_plain(self)

    def construct_sample(self, memory):
        return _HelloWorldWrapper.HelloWorldPubSubType_construct_sample(self, memory)
    __swig_setmethods__["m_md5"] = _HelloWorldWrapper.HelloWorldPubSubType_m_md5_set
    __swig_getmethods__["m_md5"] = _HelloWorldWrapper.HelloWorldPubSubType_m_md5_get
    if _newclass:
        m_md5 = _swig_property(_HelloWorldWrapper.HelloWorldPubSubType_m_md5_get, _HelloWorldWrapper.HelloWorldPubSubType_m_md5_set)
    __swig_setmethods__["m_keyBuffer"] = _HelloWorldWrapper.HelloWorldPubSubType_m_keyBuffer_set
    __swig_getmethods__["m_keyBuffer"] = _HelloWorldWrapper.HelloWorldPubSubType_m_keyBuffer_get
    if _newclass:
        m_keyBuffer = _swig_property(_HelloWorldWrapper.HelloWorldPubSubType_m_keyBuffer_get, _HelloWorldWrapper.HelloWorldPubSubType_m_keyBuffer_set)
HelloWorldPubSubType_swigregister = _HelloWorldWrapper.HelloWorldPubSubType_swigregister
HelloWorldPubSubType_swigregister(HelloWorldPubSubType)

# This file is compatible with both classic and new-style classes.


